In [69]:
import pandas as pd

In [70]:
df = pd.read_csv('pokemon_data.csv')

#excel files
#df_xlxs = pd.read_excel('pokemon_data.xlxs')

#tab selected files
#df = pd.read_csv('pokemon_data.txt', delimiter = '\t')

In [71]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [72]:
##Read Headers
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [ ]:
#Read each column
print(df['Name'])
print(df['Name', 'Type 1'],)

#Read each row
print(df.iloc[0:4])

for index, row in df.iterrows():
    print(index, row['Name'])

df.loc[df['Type 1 '] == 'Fire']

##Read a specific location(R,C)
print(df.iloc[2,1])

In [73]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [74]:
df.sort_values(['Type 1', 'HP'], ascending = [1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [75]:
#Making Changes to the data
#df['Total'] = df['HP'] + df['Attack']
# adding horizontally

df['Total'] = df.iloc[:, 4:10].sum(axis=1)
cols = list(df.columns.values)
df = df[cols[0:4] + [cols[-1]]+ cols[4:12]]
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [76]:
#Drop the column
df = df.drop(columns = ['Total'])
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [77]:
#Saving our data(desired formate)
df.to_csv ('modified.csv', index = False)
#df.to_excel('modified.xlxs', index = False)
#df.to_csv('modified_txt', index = False, sep = '\t')

In [78]:
#Filtering data
# and &
# or |
#new_df = df.loc[(df['Type 1']== 'Grass') & (df['Type 2'] == 'Poison') & (df['HP']> 70)]
#new_df = new_df.reset_index(drop =True)
#new_df
import re
df.loc[df['Type 1'].str.contains('fire|grass', flags = re.I, regex = True)]
df.loc[df['Name'].str.contains('^pi[a-z]*', flags = re.I, regex = True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False

In [79]:
#Conditional Changes
#df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'
#df.loc[df['Type 1'] == 'Flamer', 'Legendary'] = 'True'
#df.loc[df['Total']> 500, ['Generation', 'Legendary']] = ['Test 1', 'Test 2'

In [80]:
#Aggregrate Stastistics(Groupby)
df = pd.read_csv('modified.csv')
#df['Type 1'].unique
#new = df.drop_duplicates(subset=['Type 1'], keep = 'first')
#new

In [82]:
df.groupby(['Type 1']).mean(numeric_only=True).sort_values('Defense', ascending = False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408

In [86]:

df['count'] =1
df.groupby(['Type 1', 'Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

In [90]:
#Working with large amounts of data
new_df = pd.DataFrame(columns = df.columns)
for df in pd.read_csv('modified.csv', chunksize = 100):
    results = df.groupby(['Type 1']).count()
    new_df = pd.concat([new_df, results])
    print(new_df)

           # Name Type 1 Type 2  HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       11   11    NaN      9  11     11      11      11      11    11
Electric   4    4    NaN      2   4      4       4       4       4     4
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   5    5    NaN      0   5      5       5       5       5     5
Fire      11   11    NaN      3  11     11      11      11      11    11
Ghost      1    1    NaN      1   1      1       1       1       1     1
Grass     10   10    NaN     10  10     10      10      10      10    10
Ground     4    4    NaN      0   4      4       4       4       4     4
Normal    15   15    NaN     11  15     15      15      15      15    15
Poison    12   12    NaN      4  12     12      12      12      12    12
Psychic    4    4    NaN      0   4      4       4       4       4     4
Rock       3    3    NaN      3   3      3       3       3       3     3
Water     18   18    NaN      8  18     18      18      18      18    18

         Generation Legendary
Bug              11        11
Electric          4         4
Fairy             2         2
Fighting          5         5
Fire             11        11
Ghost             1         1
Grass            10        10
Ground            4         4
Normal           15        15
Poison           12        12
Psychic           4         4
Rock              3         3
Water            18        18
           # Name Type 1 Type 2  HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       11   11    NaN      9  11     11      11      11      11    11
Electric   4    4    NaN      2   4      4       4       4       4     4
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   5    5    NaN      0   5      5       5       5       5     5
Fire      11   11    NaN      3  11     11      11      11      11    11
Ghost      1    1    NaN      1   1      1       1       1       1     1
Grass     10   10    NaN     10  10     10      10      10      10    10
Ground     4    4    NaN      0   4      4       4       4       4     4
Normal    15   15    NaN     11  15     15      15      15      15    15
Poison    12   12    NaN      4  12     12      12      12      12    12
Psychic    4    4    NaN      0   4      4       4       4       4     4
Rock       3    3    NaN      3   3      3       3       3       3     3
Water     18   18    NaN      8  18     18      18      18      18    18
Bug        7    7    NaN      6   7      7       7       7       7     7
Dragon     3    3    NaN      1   3      3       3       3       3     3
Electric  10   10    NaN      2  10     10      10      10      10    10
Fairy      3    3    NaN      1   3      3       3       3       3     3
Fighting   2    2    NaN      0   2      2       2       2       2     2
Fire       6    6    NaN      1   6      6       6       6       6     6
Ghost      3    3    NaN      3   3      3       3       3       3     3
Grass      7    7    NaN      2   7      7       7       7       7     7
Ground     4    4    NaN      2   4      4       4       4       4     4
Ice        2    2    NaN      2   2      2       2       2       2     2
Normal    14   14    NaN      3  14     14      14      14      14    14
Poison     3    3    NaN      1   3      3       3       3       3     3
Psychic    9    9    NaN      4   9      9       9       9       9     9
Rock       7    7    NaN      7   7      7       7       7       7     7
Water     20   20    NaN      8  20     20      20      20      20    20

         Generation Legendary
Bug              11        11
Electric          4         4
Fairy             2         2
Fighting          5         5
Fire             11        11
Ghost             1         1
Grass            10        10
Ground            4         4
Normal           15        15
Poison           12        12
Psychic           4         4
Rock              3         3
Water            18        18
Bug               7         7
Dragon            3         3
Electric         10        10
Fairy             3         3
Fighting          2         2
Fire              6         6
Ghost             3         3
Grass             7         7
Ground            4         4
Ice               2         2
Normal           14        14
Poison            3         3
Psychic           9         9
Rock              7         7
Water            20        20
           # Name Type 1 Type 2  HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       11   11    NaN      9  11     11      11      11      11    11
Electric   4    4    NaN      2   4      4       4       4       4     4
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   5    5    NaN      0   5      5       5       5       5     5
Fire      11   11    NaN      3  11     11      11      11      11    11
Ghost      1    1    NaN      1   1      1       1       1       1     1
Grass     10   10    NaN     10  10     10      10      10      10    10
Ground     4    4    NaN      0   4      4       4       4       4     4
Normal    15   15    NaN     11  15     15      15      15      15    15
Poison    12   12    NaN      4  12     12      12      12      12    12
Psychic    4    4    NaN      0   4      4       4       4       4     4
Rock       3    3    NaN      3   3      3       3       3       3     3
Water     18   18    NaN      8  18     18      18      18      18    18
Bug        7    7    NaN      6   7      7       7       7       7     7
Dragon     3    3    NaN      1   3      3       3       3       3     3
Electric  10   10    NaN      2  10     10      10      10      10    10
Fairy      3    3    NaN      1   3      3       3       3       3     3
Fighting   2    2    NaN      0   2      2       2       2       2     2
Fire       6    6    NaN      1   6      6       6       6       6     6
Ghost      3    3    NaN      3   3      3       3       3       3     3
Grass      7    7    NaN      2   7      7       7       7       7     7
Ground     4    4    NaN      2   4      4       4       4       4     4
Ice        2    2    NaN      2   2      2       2       2       2     2
Normal    14   14    NaN      3  14     14      14      14      14    14
Poison     3    3    NaN      1   3      3       3       3       3     3
Psychic    9    9    NaN      4   9      9       9       9       9     9
Rock       7    7    NaN      7   7      7       7       7       7     7
Water     20   20    NaN      8  20     20      20      20      20    20
Bug       13   13    NaN      9  13     13      13      13      13    13
Dark       8    8    NaN      5   8      8       8       8       8     8
Electric   2    2    NaN      0   2      2       2       2       2     2
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   2    2    NaN      0   2      2       2       2       2     2
Fire       9    9    NaN      5   9      9       9       9       9     9
Ghost      1    1    NaN      0   1      1       1       1       1     1
Grass     12   12    NaN      6  12     12      12      12      12    12
Ground     3    3    NaN      1   3      3       3       3       3     3
Ice        4    4    NaN      4   4      4       4       4       4     4
Normal    13   13    NaN      2  13     13      13      13      13    13
Psychic    5    5    NaN      2   5      5       5       5       5     5
Rock       5    5    NaN      4   5      5       5       5       5     5
Steel      3    3    NaN      3   3      3       3       3       3     3
Water     18   18    NaN     13  18     18      18      18      18    18

         Generation Legendary
Bug              11        11
Electric          4         4
Fairy             2         2
Fighting          5         5
Fire             11        11
Ghost             1         1
Grass            10        10
Ground            4         4
Normal           15        15
Poison           12        12
Psychic           4         4
Rock              3         3
Water            18        18
Bug               7         7
Dragon            3         3
Electric         10        10
Fairy             3         3
Fighting          2         2
Fire              6         6
Ghost             3         3
Grass             7         7
Ground            4         4
Ice               2         2
Normal           14        14
Poison            3         3
Psychic           9         9
Rock              7         7
Water            20        20
Bug              13        13
Dark              8         8
Electric          2         2
Fairy             2         2
Fighting          2         2
Fire              9         9
Ghost             1         1
Grass            12        12
Ground            3         3
Ice               4         4
Normal           13        13
Psychic           5         5
Rock              5         5
Steel             3         3
Water            18        18
           # Name Type 1 Type 2  HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       11   11    NaN      9  11     11      11      11      11    11
Electric   4    4    NaN      2   4      4       4       4       4     4
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   5    5    NaN      0   5      5       5       5       5     5
Fire      11   11    NaN      3  11     11      11      11      11    11
Ghost      1    1    NaN      1   1      1       1       1       1     1
Grass     10   10    NaN     10  10     10      10      10      10    10
Ground     4    4    NaN      0   4      4       4       4       4     4
Normal    15   15    NaN     11  15     15      15      15      15    15
Poison    12   12    NaN      4  12     12      12      12      12    12
Psychic    4    4    NaN      0   4      4       4       4       4     4
Rock       3    3    NaN      3   3      3       3       3       3     3
Water     18   18    NaN      8  18     18      18      18      18    18
Bug        7    7    NaN      6   7      7       7       7       7     7
Dragon     3    3    NaN      1   3      3       3       3       3     3
Electric  10   10    NaN      2  10     10      10      10      10    10
Fairy      3    3    NaN      1   3      3       3       3       3     3
Fighting   2    2    NaN      0   2      2       2       2       2     2
Fire       6    6    NaN      1   6      6       6       6       6     6
Ghost      3    3    NaN      3   3      3       3       3       3     3
Grass      7    7    NaN      2   7      7       7       7       7     7
Ground     4    4    NaN      2   4      4       4       4       4     4
Ice        2    2    NaN      2   2      2       2       2       2     2
Normal    14   14    NaN      3  14     14      14      14      14    14
Poison     3    3    NaN      1   3      3       3       3       3     3
Psychic    9    9    NaN      4   9      9       9       9       9     9
Rock       7    7    NaN      7   7      7       7       7       7     7
Water     20   20    NaN      8  20     20      20      20      20    20
Bug       13   13    NaN      9  13     13      13      13      13    13
Dark       8    8    NaN      5   8      8       8       8       8     8
Electric   2    2    NaN      0   2      2       2       2       2     2
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   2    2    NaN      0   2      2       2       2       2     2
Fire       9    9    NaN      5   9      9       9       9       9     9
Ghost      1    1    NaN      0   1      1       1       1       1     1
Grass     12   12    NaN      6  12     12      12      12      12    12
Ground     3    3    NaN      1   3      3       3       3       3     3
Ice        4    4    NaN      4   4      4       4       4       4     4
Normal    13   13    NaN      2  13     13      13      13      13    13
Psychic    5    5    NaN      2   5      5       5       5       5     5
Rock       5    5    NaN      4   5      5       5       5       5     5
Steel      3    3    NaN      3   3      3       3       3       3     3
Water     18   18    NaN     13  18     18      18      18      18    18
Bug        7    7    NaN      5   7      7       7       7       7     7
Dark       4    4    NaN      2   4      4       4       4       4     4
Dragon     2    2    NaN      2   2      2       2       2       2     2
Electric   5    5    NaN      0   5      5       5       5       5     5
Fighting   5    5    NaN      3   5      5       5       5       5     5
Fire       4    4    NaN      3   4      4       4       4       4     4
Ghost      5    5    NaN      0   5      5       5       5       5     5
Grass      6    6    NaN      4   6      6       6       6       6     6
Ground     5    5    NaN      4   5      5       5       5       5     5
Ice        5    5    NaN      2   5      5       5       5       5     5
Normal    15   15    NaN      3  15     15      15      15      15    15
Poison     3    3    NaN      0   3      3       3       3       3     3
Psychic    8    8    NaN      4   8      8       8       8       8     8
Rock       7    7    NaN      6   7      7       7       7       7     7
Steel      6    6    NaN      5   6      6       6       6       6     6
Water     13   13    NaN      8  13     13      13      13      13    13

         Generation Legendary
Bug              11        11
Electric          4         4
Fairy             2         2
Fighting          5         5
Fire             11        11
Ghost             1         1
Grass            10        10
Ground            4         4
Normal           15        15
Poison           12        12
Psychic           4         4
Rock              3         3
Water            18        18
Bug               7         7
Dragon            3         3
Electric         10        10
Fairy             3         3
Fighting          2         2
Fire              6         6
Ghost             3         3
Grass             7         7
Ground            4         4
Ice               2         2
Normal           14        14
Poison            3         3
Psychic           9         9
Rock              7         7
Water            20        20
Bug              13        13
Dark              8         8
Electric          2         2
Fairy             2         2
Fighting          2         2
Fire              9         9
Ghost             1         1
Grass            12        12
Ground            3         3
Ice               4         4
Normal           13        13
Psychic           5         5
Rock              5         5
Steel             3         3
Water            18        18
Bug               7         7
Dark              4         4
Dragon            2         2
Electric          5         5
Fighting          5         5
Fire              4         4
Ghost             5         5
Grass             6         6
Ground            5         5
Ice               5         5
Normal           15        15
Poison            3         3
Psychic           8         8
Rock              7         7
Steel             6         6
Water            13        13
           # Name Type 1 Type 2  HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       11   11    NaN      9  11     11      11      11      11    11
Electric   4    4    NaN      2   4      4       4       4       4     4
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   5    5    NaN      0   5      5       5       5       5     5
Fire      11   11    NaN      3  11     11      11      11      11    11
...       ..  ...    ...    ...  ..    ...     ...     ...     ...   ...
Poison     2    2    NaN      2   2      2       2       2       2     2
Psychic    6    6    NaN      1   6      6       6       6       6     6
Rock       6    6    NaN      2   6      6       6       6       6     6
Steel      8    8    NaN      7   8      8       8       8       8     8
Water     14   14    NaN      3  14     14      14      14      14    14

         Generation Legendary
Bug              11        11
Electric          4         4
Fairy             2         2
Fighting          5         5
Fire             11        11
...             ...       ...
Poison            2         2
Psychic           6         6
Rock              6         6
Steel             8         8
Water            14        14

[75 rows x 12 columns]
           # Name Type 1 Type 2  HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       11   11    NaN      9  11     11      11      11      11    11
Electric   4    4    NaN      2   4      4       4       4       4     4
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   5    5    NaN      0   5      5       5       5       5     5
Fire      11   11    NaN      3  11     11      11      11      11    11
...       ..  ...    ...    ...  ..    ...     ...     ...     ...   ...
Poison     4    4    NaN      4   4      4       4       4       4     4
Psychic   11   11    NaN      5  11     11      11      11      11    11
Rock       4    4    NaN      1   4      4       4       4       4     4
Steel      1    1    NaN      1   1      1       1       1       1     1
Water     14   14    NaN      4  14     14      14      14      14    14

         Generation Legendary
Bug              11        11
Electric          4         4
Fairy             2         2
Fighting          5         5
Fire             11        11
...             ...       ...
Poison            4         4
Psychic          11        11
Rock              4         4
Steel             1         1
Water            14        14

[91 rows x 12 columns]
           # Name Type 1 Type 2  HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       11   11    NaN      9  11     11      11      11      11    11
Electric   4    4    NaN      2   4      4       4       4       4     4
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   5    5    NaN      0   5      5       5       5       5     5
Fire      11   11    NaN      3  11     11      11      11      11    11
...       ..  ...    ...    ...  ..    ...     ...     ...     ...   ...
Poison     2    2    NaN      0   2      2       2       2       2     2
Psychic    9    9    NaN      1   9      9       9       9       9     9
Rock       2    2    NaN      2   2      2       2       2       2     2
Steel      4    4    NaN      1   4      4       4       4       4     4
Water      8    8    NaN      6   8      8       8       8       8     8

         Generation Legendary
Bug              11        11
Electric          4         4
Fairy             2         2
Fighting          5         5
Fire             11        11
...             ...       ...
Poison            2         2
Psychic           9         9
Rock              2         2
Steel             4         4
Water             8         8

[107 rows x 12 columns]
           # Name Type 1 Type 2  HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       11   11    NaN      9  11     11      11      11      11    11
Electric   4    4    NaN      2   4      4       4       4       4     4
Fairy      2    2    NaN      0   2      2       2       2       2     2
Fighting   5    5    NaN      0   5      5       5       5       5     5
Fire      11   11    NaN      3  11     11      11      11      11    11
...       ..  ...    ...    ...  ..    ...     ...     ...     ...   ...
Poison     2    2    NaN      2   2      2       2       2       2     2
Psychic    5    5    NaN      2   5      5       5       5       5     5
Rock      10   10    NaN     10  10     10      10      10      10    10
Steel      5    5    NaN      5   5      5       5       5       5     5
Water      7    7    NaN      3   7      7       7       7       7     7

         Generation Legendary
Bug              11        11
Electric          4         4
Fairy             2         2
Fighting          5         5